apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mathtrail-observability-grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: mathtrail
  sources:
    - repoURL: https://MathTrail.github.io/charts/charts
      chart: grafana
      targetRevision: 10.5.15
      helm:
        releaseName: grafana
        valueFiles:
          - $values/values/grafana-values.yaml
    - repoURL: https://github.com/MathTrail/infra-observability
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
