apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mathtrail-storageclass
  namespace: argocd
spec:
  project: mathtrail
  source:
    repoURL: https://github.com/MathTrail/mathtrail-gitops
    path: environments/on-prem
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
