# Vault Secrets Operator (VSO) — watches VaultDynamicSecret CRs and creates K8s Secrets.
# sync-wave 4: parallel with vault-config; both depend only on Vault being running (wave 2).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: mathtrail
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault-secrets-operator
    targetRevision: 0.8.1
    helm:
      values: |
        defaultVaultConnection:
          enabled: true
          address: http://vault.vault.svc.cluster.local:8200
          skipTLSVerify: true
        controller:
          manager:
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
