# Vault initialization resources — applied after the Vault StatefulSet is ready.
# sync-wave 2: runs after vault (wave 1) is healthy.
#
# Contains:
#   - vault-unseal-key-secret.yaml: empty Secret required by Kubernetes Seal before first pod start
#   - vault-init-rbac.yaml: ServiceAccount + Role for the init Job
#   - vault-init-job.yaml: idempotent init Job that creates vault-init-credentials Secret
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-init
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: mathtrail
  source:
    repoURL: https://github.com/MathTrail/infra
    targetRevision: HEAD
    path: manifests
    directory:
      include: "vault-unseal-key-secret.yaml,vault-init-rbac.yaml,vault-init-job.yaml,vault-rbac.yaml,namespace.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
