# Vault Secrets Operator (VSO) — watches VaultDynamicSecret CRs and creates K8s Secrets.
# wave 4: parallel with vault-config; both depend only on Vault being initialized (wave 2).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: mathtrail
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault-secrets-operator
      targetRevision: 0.8.1
      helm:
        valueFiles:
          - $values/infra/values/vault-secrets-operator-values.yaml
    - repoURL: https://github.com/MathTrail/infra
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
