# Bank-Vaults Operator — manages the Vault CR lifecycle (init, unseal, configure).
# Must be deployed before the Vault instance Application.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
spec:
  project: mathtrail
  source:
    # OCI Helm chart from Bank-Vaults project.
    repoURL: ghcr.io/bank-vaults/helm-charts
    chart: vault-operator
    targetRevision: 1.22.0
    helm:
      parameters:
        - name: resources.requests.cpu
          value: "50m"
        - name: resources.requests.memory
          value: "64Mi"
        - name: resources.limits.cpu
          value: "200m"
        - name: resources.limits.memory
          value: "128Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
